CREATE TABLE usuario(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    apelido character varying(255),
    data_de_nascimento date NOT NULL,
    email character varying(255) NOT NULL,
    foto_perfil character varying(500),
    nome character varying(255) NOT NULL,
    senha character varying(255) NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT uk_email UNIQUE (email)
);


CREATE TABLE permissao(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(255),
    usuario_id bigint,
    CONSTRAINT permissao_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id)
);

CREATE TABLE solicitacao(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    situacao character varying(255),
    amigo_id bigint,
    usuario_id bigint,
    CONSTRAINT solicitacao_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id),
    CONSTRAINT fk_amigo FOREIGN KEY (amigo_id)
        REFERENCES usuario (id)
);

CREATE TABLE amizade(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amigo_id bigint,
    solicitacao_id bigint,
    usuario_id bigint,
    CONSTRAINT amizade_pkey PRIMARY KEY (id),
    CONSTRAINT fk_solicitacao FOREIGN KEY (solicitacao_id) REFERENCES solicitacao (id),
    CONSTRAINT fk_amigo FOREIGN KEY (amigo_id) REFERENCES usuario (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE TABLE postagem(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    conteudo character varying(255) NOT NULL,
    horario timestamp without time zone,
    titulo character varying(255) NOT NULL,
    visibilidade character varying(255) NOT NULL,
    usuario_id bigint,
    CONSTRAINT postagem_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id)
);

CREATE TABLE comentario(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    comentario character varying(255) NOT NULL,
    horario timestamp without time zone,
    postagem_id bigint,
    usuario_id bigint,
    CONSTRAINT comentario_pkey PRIMARY KEY (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id),
    CONSTRAINT fk_postagem FOREIGN KEY (postagem_id)
        REFERENCES postagem (id)
);

CREATE TABLE curtida(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    horario timestamp without time zone,
    postagem_id bigint,
    usuario_id bigint,
    CONSTRAINT curtida_pkey PRIMARY KEY (id),
    CONSTRAINT fk_postagem FOREIGN KEY (postagem_id)
        REFERENCES postagem (id),
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id)
);



